OPENAI_API_KEY="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"
PINECONE_API_KEY="pcsk_2W2cLq_2YiHYwPH3iCnMpYuCZnBTcKHuLZBvVeHYKNafHHNrCDpKexe8HDkAniZvmxHHAh"
directory = "path/to/pdf_directory"
index_name = "hr-policies-index"
